######################################################
#                   SPECIALS 18.5                    #
######################################################

templates:
  Rating:
    collection_order: custom
    sync_mode: sync

  Special:
    smart_label: random
    sync_mode: sync
    sort_title: zz__<<collection_name>>
    visible_library: true

  Special Other:
    smart_label: random
    sync_mode: sync
    visible_library: false

  Special Smart:
    sync_mode: sync
    visible_library: true

  Special Smart Other:
    sync_mode: sync
    sort_title: zz__<<collection_name>>
    visible_library: false

  Season:
    collection_order: custom
    sync_mode: sync
    sort_title: zz__<<collection_name>>
    visible_library: true

collections:
  18+: # Sorts every anime with an adult rating
    template: { name: Special Smart }
    sort_title: zz___18+
    summary: Animes with this rating are generally not suitable for children or individuals under 17 (some sources may say 18). This content is only made for mature audiences because it contains mature themes, such as gore, sexual violence, strong language, nudity, substances, smoking, and sex.
    file_poster: config/posters/18+ Anime.png
    smart_filter:
      sort_by: random
      validate: false
      all:
        content_rating: TV-MA

  480P+: # Animes with a quality of 240p to 576p
    template: { name: Special Other }
    summary: Animes in SD, 480p and 576p quality.
    sort_title: zz___21_480P+
    file_poster: config/posters/480P+.png
    plex_search:
      any:
        resolution:
          - SD
          - 480p
          - 576p

  720P:
    template: { name: Special Other }
    summary: Animes in 720p quality.
    sort_title: zz___22_720P
    file_poster: config/posters/720P.png
    plex_search:
      all:
        resolution: 720p

  1080P:
    template: { name: Special Other }
    summary: Animes in 1080p quality.
    sort_title: zz___23_1080P
    file_poster: config/posters/1080P.png
    plex_search:
      all:
        resolution: 1080p

  Award Winning: # MyAnimeList specific awards list
    template: { name: Special }
    mal_search:
      genre: 46
      limit: 500
    summary: Titles which have won prestigious or professional awards in Japan. Examples include the Tokyo Anime Award or Japan Media Arts Festival awards.
    file_poster: config/posters/Award Winning.png

  Favored: # Fetched information from Tautulli
    template: { name: Special Smart Other }
    tautulli_popular:
      list_days: 62
      list_size: 20
      list_minimum: 1
    tautulli_watched:
      list_days: 62
      list_size: 20
      list_minimum: 1
    smart_label: viewed.desc
    file_poster: config/posters/Favored.png
    summary: The most favored Animes on Plex by users the past 2 months.

  Newly Released:
    template: { name: Special Smart Other }
    visible_library: true
    file_poster: config/posters/Newly Released.png
    summary: Animes recently released in the past 2 months.
    sonarr_add_missing: true
    sonarr_add_existing: true
    sonarr_monitor_existing: true
    trakt_list: https://trakt.tv/users/jhn322/lists/upcoming-anime?sort=rank,asc

  Random: # Random animes with a rating above 4 from mal
    template: { name: Special Smart Other }
    file_poster: config/posters/Random.png
    summary: Random Animes.
    smart_filter:
      sort_by: random
      limit: 50
      validate: false
      all:
        audience_rating.gte: 4.0

  Watched: # Fetched information from Tautulli
    template: { name: Special }
    visible_library: false
    tautulli_watched:
      list_days: 9999
      list_size: 9999
      list_minimum: 1
    file_poster: config/posters/Watched.png
    summary: Animes watched on Plex by all users.
    smart_label: viewed.desc

  Worst: # Animes rating with less 5 in rating from mal
    template: { name: Special Smart Other }
    summary: Worst animes on Plex rated 5.0 or lower.
    visible_library: false
    file_poster: config/posters/Worst.png
    smart_filter:
      sort_by: audience_rating.asc
      validate: false
      all:
        audience_rating.lte: 5.0

  #############################################################################
  #               WATCHED AIMES WITH USER SPECIFIC RATINGS 2.0                #
  #                                                                           #
  # Create 5 lists on Trakt and sort animes you've watched by your preference.#
  #      For example: "Kill la Kill" 8/10. Then uncomment everything and      #
  #               simply add each corresponding list down below.              #
  #############################################################################
  # 10/10:
  #   template: { name: Rating }
  #   summary: Animes with a user rating of 10/10 (sorted from best to worst).
  #   sort_title: zzzzzzzzzz_10/10
  #   file_poster: config/posters/10.png
  #   trakt_list:

  # 9/10:
  #   template: { name: Rating }
  #   summary: Animes with a user rating of 9/10 (sorted from best to worst).
  #   sort_title: zzzzzzzzz_9/10
  #   file_poster: config/posters/9.png
  #   trakt_list:

  # 8/10:
  #   template: { name: Rating }
  #   summary: Animes with a user rating of 8/10 (sorted from best to worst).
  #   sort_title: zzzzzzzz_8/10
  #   file_poster: config/posters/8.png
  #   trakt_list:

  # 7/10:
  #   template: { name: Rating }
  #   summary: Animes with a user rating of 7/10 (sorted from best to worst).
  #   sort_title: zzzzzzz_7/10
  #   file_poster: config/posters/7.png
  #   trakt_list:

  # 6/10:
  #   template: { name: Rating }
  #   summary: Animes with a user rating of 6/10 (sorted from best to worst).
  #   sort_title: zzzzzz_6/10
  #   file_poster: config/posters/6.png
  #   trakt_list:

  # 1-5/10:
  #   template: { name: Rating }
  #   summary: Animes with a user rating of 1-5/10 (sorted from best to worst).
  #   sort_title: zzzzzzzz_1-5/10
  #   file_poster: config/posters/1-5.png
  #   trakt_list:
