# Adds the specific resolution overlay to all qualified animes
templates:
  # Uncomment to use any of these optional resolution templates and(!) the corresponding overlays below
  # 1080PDV:
  #   optional:
  #     - overlay_level
  #     - use_<<opt1>>
  #     - use_<<opt2>>
  #   default:
  #     overlay: <<overlay_name>>
  #   collection_level: <<overlay_level>>
  #   overlay:
  #     name: <<overlay_name>>
  #     file_poster: config/overlays/1080P-DV.png

  # 1080PHDR10+:
  #   optional:
  #     - overlay_level
  #   default:
  #     overlay: <<overlay_name>>
  #   collection_level: <<overlay_level>>
  #   overlay:
  #     name: <<overlay_name>>
  #     file_poster: config/overlays/1080P-HDR10+.png

  # 1080PHDR:
  #   optional:
  #     - overlay_level
  #     - use_<<opt1>>
  #     - use_<<opt2>>
  #   default:
  #     overlay: <<overlay_name>>
  #   collection_level: <<overlay_level>>
  #   overlay:
  #     name: <<overlay_name>>
  #     file_poster: config/overlays/1080P-HDR.png

  # 1080PFHD:
  #   optional:
  #     - overlay_level
  #   default:
  #     overlay: <<overlay_name>>
  #   collection_level: <<overlay_level>>
  #   overlay:
  #     name: <<overlay_name>>
  #     file_poster: config/overlays/1080P-FHD.png

  # 720PHD:
  #   optional:
  #     - overlay_level
  #   default:
  #     overlay: <<overlay_name>>
  #   collection_level: <<overlay_level>>
  #   overlay:
  #     name: <<overlay_name>>
  #     file_poster: config/overlays/720P-HD.png

  576PSD:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      file_poster: config/overlays/576P.png

  480PSD:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      file_poster: config/overlays/480P.png

  240PSD:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      file_poster: config/overlays/240P.png

# Sorted by priority from most to least important
overlays:
  # Uncomment to use any of these optional resolution overlays and(!) the corresponding templates above
  # 1080P-DV:
  #   template:
  #     - name: 1080PDV
  #       opt1: 1080p
  #       opt2: dv
  #   suppress_overlays:
  #     - 1080P-HDR10+
  #     - 1080P-HDR
  #     - 1080P-FHD
  #     - 720p
  #     - 576P
  #     - 480P
  #     - 240P
  #   plex_search:
  #     all:
  #       resolution.regex: "(?i)1080|2k"
  #   filters:
  #     has_dolby_vision: true

  # 1080P-HDR10+:
  #   template:
  #     - name: 1080PHDR10+
  #   suppress_overlays:
  #     - 1080P-HDR
  #     - 1080P-FHD
  #     - 720p
  #     - 576P
  #     - 480P
  #     - 240P
  #   plex_search:
  #     all:
  #       resolution.regex: "(?i)1080|2k"
  #   filters:
  #     has_dolby_vision: false
  #     filepath.regex: (?i)\bhdr10(\+|p(lus)?\b)

  # 1080P-HDR:
  #   template:
  #     - name: 1080PHDR
  #       opt1: 1080p
  #       opt2: hdr
  #   suppress_overlays:
  #     - 1080P-FHD
  #     - 720p
  #     - 576P
  #     - 480P
  #     - 240P
  #   plex_search:
  #     all:
  #       resolution.regex: "(?i)1080|2k"
  #       hdr: true
  #   filters:
  #     has_dolby_vision: false

  # 1080P-FHD:
  #   template:
  #     - name: 1080PFHD
  #   suppress_overlays:
  #     - 720p
  #     - 576P
  #     - 480P
  #     - 240P
  #   plex_search:
  #     all:
  #       resolution: 1080p
  #   filters:
  #     has_dolby_vision: false
  #     filepath.regex: "(?i)^((?!hdr).)*$"

  # 720P:
  #   template:
  #     - name: 720PHD
  #   suppress_overlays:
  #     - 576P
  #     - 480P
  #     - 240P
  #   plex_search:
  #     all:
  #       resolution: 720p

  576P:
    template:
      - name: 576PSD
    suppress_overlays:
      - 480P
      - 240P
    plex_search:
      all:
        resolution: 576p

  480P:
    template:
      - name: 480PSD
    suppress_overlays:
      - 240P
    plex_search:
      all:
        resolution: 480p

  240P:
    template:
      - name: 240PSD
    plex_search:
      all:
        resolution: sd
