# Adds a top overlay to all qualified animes depending if it's from mal or anilist
templates:
  MAL Top:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    mal_tv: 500
    overlay:
      name: <<overlay_name>>

  AL Top:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    anilist_top_rated: 300
    overlay:
      name: <<overlay_name>>

# Sorted by priority from most to least important
overlays:
  MAL-Top:
    template:
      - name: MAL Top
    suppress_overlays:
      - AL-Top

  AL-Top:
    template:
      - name: AL Top
