#####################################################
#                 HOLIDAYS 5.0                      #
#####################################################

templates:
  Holiday:
    sort_title: ZZZZZZZZZZZZZZZZZZZ+<<collection_name>>
    # smart_label: random not working as of 231114
    sync_mode: sync
    visible_home: false

# Holiday collections that will show up when the holiday has started and disappear when it has ended
collections:
  Christmas ğŸ„:
    template: { name: Holiday }
    visible_home: range(12/01-12/31)
    visible_shared: range(12/01-12/31)
    summary: Ho ho ho.
    file_poster: config/posters/Christmas.png
    trakt_list:
      - https://trakt.tv/users/ad76/lists/hallmark-christmas?sort=released,asc
      - https://trakt.tv/users/plexmetamanager/lists/christmas-extravaganza-non-tv-movie?sort=released,asc
      - https://trakt.tv/users/movistapp/lists/christmas-movies
      - https://trakt.tv/users/questdvd/lists/absolute-hayes-christmas-classics
      - https://trakt.tv/users/littlestella3/lists/christmas

  Easter ğŸ£:
    template: { name: Holiday }
    visible_home: range(03/20-04/30)
    visible_shared: range(03/20-04/30)
    summary: The Easter bunny is here!
    file_poster: config/posters/Easter.png
    trakt_list:
      - https://trakt.tv/users/smwixted/lists/easter?sort=votes,asc
      - https://trakt.tv/users/tarzanislav/lists/easter?sort=added,asc

  Fathers Day ğŸ‘¨â€ğŸ‘¦:
    template: { name: Holiday }
    visible_home: range(11/09-11/14)
    visible_shared: range(11/09-11/14)
    summary: Every Fathers Special day.
    file_poster: config/posters/Fathers Day.png
    trakt_list:
      - https://trakt.tv/users/fcisco13/lists/dad-movies?sort=rank,asc
      - https://trakt.tv/users/segfaulted/lists/movies-for-dad?sort=rank,asc

  Halloween ğŸƒ:
    template: { name: Holiday }
    visible_home: range(10/01-10/31)
    visible_shared: range(10/01-10/31)
    summary: This is Halloween!
    file_poster: config/posters/Halloween..png
    trakt_list:
      - https://trakt.tv/users/29zombies/lists/halloween
      - https://trakt.tv/users/galacticboy/lists/not-so-spooky-halloween
      - https://trakt.tv/users/kairbear08/lists/halloween
      - https://trakt.tv/users/mybicycle/lists/halloween

  Mothers Day ğŸ‘©â€ğŸ‘§:
    template: { name: Holiday }
    visible_home: range(05/22-05/29)
    visible_shared: range(05/22-05/29)
    summary: Every Mothers special day.
    file_poster: config/posters/Mothers Day.png
    trakt_list:
      - https://trakt.tv/users/movie-pal/lists/mother-s-day?sort=rank,asc
      - https://trakt.tv/users/mdm144/lists/mother-s-day?sort=rank,asc

  New Years ğŸ¾:
    template: { name: Holiday }
    visible_home: range(12/31-01/06)
    visible_shared: range(12/31-01/06)
    summary: Happy New Year!
    file_poster: config/posters/New Year.png
    trakt_list:
      - https://trakt.tv/users/gullibletransport/lists/new-year?sort=random,asc
      - https://trakt.tv/users/sympli/lists/new-years-movies?sort=rank,asc
      - https://trakt.tv/users/padawan_seneca/lists/new-years-eve?sort=rank,asc
      - https://trakt.tv/users/galacticboy/lists/new-years?sort=rank,asc

  Valentines Day ğŸ’˜:
    template: { name: Holiday }
    visible_home: range(02/14-02/15)
    visible_shared: range(02/14-02/15)
    summary: Love me tender, love me sweet.
    file_poster: config/posters/Valentines Day.png
    trakt_list:
      - https://trakt.tv/users/movie-pal/lists/valentine-s-day
      - https://trakt.tv/users/barsaky/lists/den-svateho-valentina-valentine-s-day
      - https://trakt.tv/users/abbelea/lists/movies-best-of-love
