#####################################################
#                   DECADES 7.0                     #
#####################################################
templates:
  Decade:
    smart_label: audience_rating.desc
    sync_mode: sync
    sort_title: +<<collection_name>>
    visible_library: true

  Year:
    smart_label: audience_rating.desc
    sync_mode: sync
    sort_title: ZZZZZ+<<collection_name>>
    visible_library: true

collections:
  Best of 1920s:
    template: { name: Decade }
    plex_search:
      all:
        year.gt: 1919
        year.lt: 1930
        audience_rating.gte: 7.0
    limit: 500
    visible_shared: range(10/01-10/15)
    file_poster: config/posters/1920s.png

  Best of 1930s:
    template: { name: Decade }
    plex_search:
      all:
        year.gt: 1929
        year.lt: 1940
        audience_rating.gte: 7.0
    limit: 500
    visible_shared: range(06/01-06/15)
    file_poster: config/posters/1930s.png

  Best of 1940s:
    template: { name: Decade }
    plex_search:
      all:
        year.gt: 1939
        year.lt: 1950
        audience_rating.gte: 7.0
    limit: 500
    visible_shared: range(04/01-04/15)
    file_poster: config/posters/1940s.png

  Best of 1950s:
    template: { name: Decade }
    plex_search:
      all:
        year.gt: 1949
        year.lt: 1960
        audience_rating.gte: 7.0
    limit: 500
    visible_shared: range(12/01-12/15)
    file_poster: config/posters/1950s.png

  Best of 1960s:
    template: { name: Decade }
    plex_search:
      all:
        year.gt: 1959
        year.lt: 1970
        audience_rating.gte: 7.0
    limit: 500
    visible_shared: range(03/01-03/15)
    file_poster: config/posters/1960s.png

  Best of 1970s:
    template: { name: Decade }
    plex_search:
      all:
        year.gt: 1969
        year.lt: 1980
        audience_rating.gte: 7.0
    limit: 500
    visible_shared: range(07/01-07/15)
    file_poster: config/posters/1970s.png

  Best of 1980s:
    template: { name: Decade }
    plex_search:
      all:
        year.gt: 1979
        year.lt: 1990
        audience_rating.gte: 7.0
    limit: 500
    visible_shared: range(01/01-01/15)
    file_poster: config/posters/1980s.png

  Best of 1990s:
    template: { name: Decade }
    plex_search:
      all:
        year.gt: 1989
        year.lt: 2000
        audience_rating.gte: 7.0
    limit: 500
    visible_shared: range(11/01-11/15)
    file_poster: config/posters/1990s.png

  Best of 2000s:
    template: { name: Decade }
    plex_search:
      all:
        year.gt: 1999
        year.lt: 2010
        audience_rating.gte: 7.0
    limit: 500
    visible_shared: range(09/01-09/15)
    file_poster: config/posters/2000s.png

  Best of 2010s:
    template: { name: Decade }
    plex_search:
      all:
        year.gt: 2009
        year.lt: 2020
        audience_rating.gte: 7.0
    limit: 500
    visible_shared: range(05/01-05/15)
    file_poster: config/posters/2010s.png

  Best of 2020s:
    template: { name: Decade }
    plex_search:
      all:
        year.gt: 2019
        year.lt: 2030
        audience_rating.gte: 7.0
    limit: 500
    visible_shared: range(02/01-02/15)
    file_poster: config/posters/2020s.png

  ######################################################
  #                   YEARS 4.0                      #
  ######################################################

  Best of 2000:
    template: { name: Year }
    file_poster: config/posters/2000.png
    visible_shared: range(03/23-04/01)
    plex_search:
      all:
        year: 2000
        audience_rating.gte: 7.0

  Best of 2001:
    template: { name: Year }
    file_poster: config/posters/2001.png
    visible_shared: range(05/16-05/22)
    plex_search:
      all:
        year: 2001
        audience_rating.gte: 7.0

  Best of 2002:
    template: { name: Year }
    file_poster: config/posters/2002.png
    visible_shared: range(07/16-07/22)
    plex_search:
      all:
        year: 2002
        audience_rating.gte: 7.0

  Best of 2003:
    template: { name: Year }
    file_poster: config/posters/2003.png
    visible_shared: range(06/23-06/30)
    plex_search:
      all:
        year: 2003
        audience_rating.gte: 7.0

  Best of 2004:
    template: { name: Year }
    file_poster: config/posters/2004.png
    visible_shared: range(04/02-04/15)
    plex_search:
      all:
        year: 2004
        audience_rating.gte: 7.0

  Best of 2005:
    template: { name: Year }
    file_poster: config/posters/2005.png
    visible_shared: range(08/01-08/15)
    plex_search:
      all:
        year: 2005
        audience_rating.gte: 7.0

  Best of 2006:
    template: { name: Year }
    file_poster: config/posters/2006.png
    visible_shared: range(05/23-05/31)
    plex_search:
      all:
        year: 2006
        audience_rating.gte: 7.0

  Best of 2007:
    template: { name: Year }
    file_poster: config/posters/2007.png
    visible_shared: range(07/23-07/30)
    plex_search:
      all:
        year: 2007
        audience_rating.gte: 7.0

  Best of 2008:
    template: { name: Year }
    file_poster: config/posters/2008.png
    visible_shared: range(01/16-01/22)
    plex_search:
      all:
        year: 2008
        audience_rating.gte: 7.0

  Best of 2009:
    template: { name: Year }
    file_poster: config/posters/2009.png
    visible_shared: range(01/23-01/31)
    plex_search:
      all:
        year: 2009
        audience_rating.gte: 7.0

  Best of 2010:
    template: { name: Year }
    file_poster: config/posters/2010.png
    visible_shared: range(04/16-04/30)
    plex_search:
      all:
        year: 2010
        audience_rating.gte: 7.0

  Best of 2011:
    template: { name: Year }
    file_poster: config/posters/2011.png
    visible_shared: range(10/23-10/31)
    plex_search:
      all:
        year: 2011
        audience_rating.gte: 7.0

  Best of 2012:
    template: { name: Year }
    file_poster: config/posters/2012.png
    visible_shared: range(06/01-06/15)
    plex_search:
      all:
        year: 2012
        audience_rating.gte: 7.0

  Best of 2013:
    template: { name: Year }
    file_poster: config/posters/2013.png
    visible_shared: range(12/16-12/31)
    plex_search:
      all:
        year: 2013
        audience_rating.gte: 7.0

  Best of 2014:
    template: { name: Year }
    file_poster: config/posters/2014.png
    visible_shared: range(02/01-02/15)
    plex_search:
      all:
        year: 2014
        audience_rating.gte: 7.0

  Best of 2015:
    template: { name: Year }
    file_poster: config/posters/2015.png
    visible_shared: range(06/16-06/22)
    plex_search:
      all:
        year: 2015
        audience_rating.gte: 7.0

  Best of 2016:
    template: { name: Year }
    file_poster: config/posters/2016.png
    visible_shared: range(12/01-12/15)
    plex_search:
      all:
        year: 2016
        audience_rating.gte: 7.0

  Best of 2017:
    template: { name: Year }
    file_poster: config/posters/2017.png
    visible_shared: range(10/01-10/15)
    plex_search:
      all:
        year: 2017
        audience_rating.gte: 7.0

  Best of 2018:
    template: { name: Year }
    file_poster: config/posters/2018.png
    visible_shared: range(02/16-02/28)
    plex_search:
      all:
        year: 2018
        audience_rating.gte: 7.0

  Best of 2019:
    template: { name: Year }
    file_poster: config/posters/2019.png
    visible_shared: range(08/16-08/31)
    plex_search:
      all:
        year: 2019
        audience_rating.gte: 7.0

  Best of 2020:
    template: { name: Year }
    file_poster: config/posters/2020.png
    visible_shared: range(11/16-11/30)
    plex_search:
      all:
        year: 2020
        audience_rating.gte: 7.0

  Best of 2021:
    template: { name: Year }
    file_poster: config/posters/2021.png
    visible_shared: range(09/16-09/31)
    plex_search:
      all:
        year: 2021
        audience_rating.gte: 7.0

  Best of 2022:
    template: { name: Year }
    file_poster: config/posters/2022.png
    visible_shared: range(10/16-10/22)
    plex_search:
      all:
        year: 2022
        audience_rating.gte: 7.0

  Best of 2023:
    template: { name: Year }
    file_poster: config/posters/2023.png
    visible_shared: range(03/16-03/22)
    plex_search:
      all:
        year: 2023
        audience_rating.gte: 7.0
