######################################################
#                   MUSIC 2.0                        #
######################################################
templates:
  Standard:
    sort_title: +++_<<collection_name>>
    visible_library: true

collections:
  Popular:
    template: { name: Standard }
    summary: Most popular artists on Plex with at least 10 track plays on minimum 1 song.
    file_poster: config/posters/Popular Music.png
    smart_filter:
      all:
        track_plays.gte: 10
      sort_by: plays.desc
