# Adds a top overlay to all qualified TV shows from IMDb, Trakt and TMDb
templates:
  IMDB Top:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    imdb_chart: top_movies
    overlay:
      name: <<overlay_name>>

  Trakt Top:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: https://trakt.tv/users/patricafdw/lists/trakt-top-movies
    overlay:
      name: <<overlay_name>>

  Letterboxd Top:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    trakt_list: https://trakt.tv/users/abdulwahabaa/lists/letterboxd-top-250?sort=rank,asc
    overlay:
      name: <<overlay_name>>

  TMDB Top:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    tmdb_top_rated: 300
    overlay:
      name: <<overlay_name>>

  MAL Top:
    optional:
      - overlay_level
    default:
      overlay: <<overlay_name>>
    collection_level: <<overlay_level>>
    mal_movie: 500
    overlay:
      name: <<overlay_name>>

# Sorted by priority from most to least important
overlays:
  IMDB-Top:
    template:
      - name: IMDB Top
    suppress_overlays:
      - Trakt-Top
      - Letterboxd-Top
      - TMDB-Top
      - MAL-Top

  Trakt-Top:
    template:
      - name: Trakt Top
    suppress_overlays:
      - Letterboxd-Top
      - TMDB-Top
      - MAL-Top

  Letterboxd-Top:
    template:
      - name: Letterboxd Top
    suppress_overlays:
      - TMDB-Top
      - MAL-Top

  TMDB-Top:
    template:
      - name: TMDB Top
    suppress_overlays:
      - MAL-Top

  MAL-Top:
    template:
      - name: MAL Top
