######################################################
#                    TV 17.5                         #
######################################################

templates:
  TV:
    smart_label: random
    sync_mode: sync
    sort_title: +++++_<<collection_name>>
    visible_library: true

  TV Release:
    smart_label: release.desc
    sync_mode: sync
    sort_title: +++++_<<collection_name>>
    visible_library: true

  TV Top:
    sync_mode: sync
    visible_library: true

collections:
  IMDb - Best Recent: # IMDb specific chart lists
    template: { name: TV Top }
    summary: TV shows rated 7.5 or higher on IMDb, released in the past 3 months.
    sort_title: +++++++_ZIMDb Best Recent
    visible_shared:
      - monthly(11)
      - monthly(12)
    file_poster: config/posters/IMDb Best Recent.png
    smart_filter:
      sort_by: audience_rating.desc
      validate: false
      all:
        audience_rating.gte: 7.7
        release: 90

  IMDb - Top 250:
    template: { name: TV Top }
    smart_label: audience_rating.desc
    sort_title: +++++++_IMDB top 250
    file_poster: config/posters/IMDb Top 250 Gold.png
    visible_shared:
      - monthly(4)
      - monthly(9)
    trakt_list: https://trakt.tv/users/justin/lists/imdb-top-rated-tv-shows?sort=rank,asc

  Metacritic - Must-See: # Metacritic specific chart lists
    template: { name: TV }
    visible_shared:
      - monthly(14)
      - monthly(31)
    summary: Metacritic labels a show as "Must-See" when it achieves a Metascore of 81 or higher and has been reviewed by a minimum of 15 professional critics.
    file_poster: config/posters/Metacritic Must See.png
    trakt_list: https://trakt.tv/users/k0meta/lists/metacritic-must-see-shows

  Popular: # Popular list from Trakt and TMDb
    template: { name: TV }
    tmdb_popular: 150
    sort_title: ++++++++_XPopular
    visible_shared:
      - monthly(10)
      - monthly(12)
      - monthly(22)
      - monthly(7)
      - monthly(8)
    trakt_chart:
      chart: popular
      limit: 40
    visible_library: true
    file_poster: config/posters/Popular.png
    summary: Popular shows on IMDb, Trakt and TMDb over the past few months.
    trakt_list: https://trakt.tv/users/justin/lists/imdb-popular-tv-shows?sort=rank,asc

  RT - Certified Fresh: # Rotten Tomatoes specific chart lists
    template: { name: TV }
    limit: 150
    visible_shared:
      - monthly(13)
      - monthly(6)
    summary: Certified fresh A special distinction awarded to the best reviewed TV Shows.
    file_poster: config/posters/Rotten Tomatoes Certified Fresh.png
    trakt_list: https://trakt.tv/users/k0meta/lists/certified-fresh-shows

  TMDb - On the Air: # TMDb specific chart lists
    template: { name: TV Release }
    tmdb_on_the_air: 80
    tmdb_airing_today: 40
    visible_shared: monthly(1)
    file_poster: config/posters/TMDb On the Air.png
    summary: Shows airing right now across streaming services.

  Top Rated: # Top rated list from Trakt and TMDb
    template: { name: TV }
    tmdb_top_rated: 300
    sort_title: ++++++++_Top Rated
    visible_shared:
      - monthly(17)
      - monthly(18)
      - monthly(2)
      - monthly(11)
      - monthly(16)
      - monthly(15)
    file_poster: config/posters/Top Rated.png
    summary: Top Rated Shows on Trakt and TMDb.
    trakt_list: https://trakt.tv/users/jason316/lists/trakt-yearly-top-tv?sort=released,asc

  Trakt - Most Watched (All-Time): # Trakt specific chart lists
    template: { name: TV }
    trakt_chart:
      chart: watched
      limit: 220
      time_period: all
    file_poster: config/posters/Trakt Most Watched All-Time.png
    visible_shared:
      - monthly(28)
      - monthly(25)
    summary: Movies most watched online of all time.

  Trakt - Most Watched (Yearly):
    template: { name: TV }
    trakt_chart:
      chart: watched
      limit: 60
      time_period: yearly
    file_poster: config/posters/Trakt Most Watched Yearly.png
    summary: Most watched shows across the internet this year.
    visible_shared: monthly(23)

  Trakt - Recommended:
    template: { name: TV }
    trakt_recommendations: 30
    sort_title: ++++++_Trakt - Recommended
    summary: Shows recommended by trakt API.
    file_poster: config/posters/Trakt Recommended.png
    visible_shared:
      - monthly(29)
      - monthly(30)

  Trending: # Trending list from Trakt and TMDb
    template: { name: TV Release }
    tmdb_trending_weekly: 30
    trakt_chart:
      chart: trending
      limit: 30
    sort_title: ++++++++_ZTrending
    visible_shared:
      - monthly(26)
      - monthly(24)
      - monthly(21)
    file_poster: config/posters/Trending.png
    summary: Shows trending on Trakt and TMDb this week.
