######################################################
#                SEPARATORS 3.0                      #
######################################################
templates:
  Separator:
    smart_label: random
    sync_mode: sync
    plex_search:
      all:
        title: breaking bad

# Creates a separator to make it more clear where a category of collection starts and ends
collections:
  Award Collections:
    template: { name: Separator }
    sort_title: zzz_<<AAA
    summary: Award collections up next.
    file_poster: config/posters/Award Collections.png

  Chart Collections:
    template: { name: Separator }
    sort_title: ++++++_ZZZ
    summary: Chart collections up next.
    file_poster: config/posters/Chart Collections.png

  Decade Collections:
    template: { name: Separator }
    sort_title: zzzz_AAA
    summary: Decade collections up next.
    file_poster: config/posters/Decade Collections.png

  Franchise Collections:
    template: { name: Separator }
    sort_title: zzzzzzz_<<
    summary: Franchise collections up next.
    file_poster: config/posters/Franchise Collections.png

  Genre Collections:
    template: { name: Separator }
    sort_title: +01_AAA
    summary: Genre collections up next.
    file_poster: config/posters/Genre Collections.png

  Network Collections:
    template: { name: Separator }
    sort_title: zzzzzz_1AAA
    summary: Network collections up next.
    file_poster: config/posters/Network Collections.png

  Rating Collections:
    template: { name: Separator }
    sort_title: zzzzzzzz_11
    summary: Rating collections up next.
    file_poster: config/posters/Rating Collections.png

  Special Collections:
    template: { name: Separator }
    sort_title: zz_000
    summary: Special collections up next.
    file_poster: config/posters/Special Collections.png

  Streaming Collections:
    template: { name: Separator }
    sort_title: ++_AAA
    summary: Streaming collections up next.
    file_poster: config/posters/Streaming Collections.png

  Subgenre Collections:
    template: { name: Separator }
    sort_title: +02_AAA
    summary: Subgenre collections up next.
    file_poster: config/posters/Subgenre Collections.png

  Year Collections:
    template: { name: Separator }
    sort_title: zzzzz_AAA
    summary: Year collections up next.
    file_poster: config/posters/Year Collections.png
