#############################################################
#                       AWARDS 8.0                          #
#############################################################

templates:
  imdb:
    optional:
      - trakt_list
    sort_title: "zzzzz_<<num>>_<<collection_name>>"
    sync_mode: sync
    smart_label: release.desc
    delete_not_scheduled: false
    trakt_list:
      - <<trakt_list>>

  letterboxd:
    optional:
      - letterboxd_extra_1
      - letterboxd_extra_2
      - letterboxd_extra_3
      - letterboxd_extra_4
      - letterboxd_extra_5
    sort_title: "zzzzz_<<num>>_<<collection_name>>"
    sync_mode: sync
    smart_label: release.desc
    delete_not_scheduled: false
    letterboxd_list:
      url: https://letterboxd.com/<<user>>/list/<<list>>/by/<<sort>>
      limit: 9999

  custom:
    optional:
      - trakt_list
    sort_title: "zzzzz_<<num>>_<<collection_name>>"
    sync_mode: sync
    smart_label: release.desc
    delete_not_scheduled: false
    imdb_list:
      url: https://www.imdb.com/list/<<imdb_list>>/?sort=release_date,desc
      limit: 9999

# TV shows who has won some the most prestigious awards
collections:
  BAFTA - Nominees:
    template: { name: imdb }
    summary: "A collection of BAFTA Nominees"
    file_poster: config/posters/BAFTA Nominees.png
    imdb_award:
      event_id: "ev0000123"
      event_year: "1949-current"
      winning: false
      type: "tv_series,tv_special,tv_mini_series"
      language: "en"
      sort_by: release.desc
      limit: 9999

  BAFTA - Winners:
    template: { name: imdb }
    summary: "A collection of BAFTA Winners"
    visible_shared: monthly(10)
    file_poster: config/posters/BAFTA Winners.png
    imdb_award:
      event_id: "ev0000123"
      event_year: "1949-current"
      winning: true
      type: "tv_series,tv_special,tv_mini_series"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Critics Choice Awards - Nominees:
    template: { name: imdb }
    summary: "A collection of Critics Choice Award Nominees"
    file_poster: config/posters/Critics Choice Nominees.png
    imdb_award:
      event_id: "ev0000133"
      event_year: "1996-current"
      winning: false
      type: "tv_series,tv_special,tv_mini_series"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Critics Choice Awards - Winners:
    template: { name: imdb }
    summary: "A collection of Critics Choice Award Winners"
    visible_shared: monthly(5)
    file_poster: config/posters/critics choice winners.png
    imdb_award:
      event_id: "ev0000133"
      event_year: "1996-current"
      winning: true
      type: "tv_series,tv_special,tv_mini_series"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Emmy - Winners:
    template: { name: imdb }
    summary: "A collection of Emmy Award Winners"
    visible_library: true
    visible_shared: monthly(20)
    file_poster: config/posters/Emmy Winners.png
    imdb_award:
      event_id: "ev0000223"
      event_year: "1949-current"
      winning: true
      type: "tv_series,tv_special,tv_mini_series"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Emmy - Nominees:
    template: { name: imdb }
    summary: "A collection of Emmy Award Nominees"
    file_poster: config/posters/Emmy Nominees.png
    imdb_award:
      event_id: "ev0000223"
      event_year: "1949-current"
      winning: false
      type: "tv_series,tv_special,tv_mini_series"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Golden Globe - Nominees:
    template: { name: imdb }
    summary: "A collection of Golden Globes Nominees"
    file_poster: config/posters/Golden Globe Nominees.png
    imdb_award:
      event_id: "ev0000292"
      event_year: "1944-current"
      winning: false
      type: "tv_series,tv_special,tv_mini_series"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Golden Globe - Winners:
    template: { name: imdb }
    summary: "A collection of Golden Globes Winners"
    visible_shared: monthly(15)
    file_poster: config/posters/Golden Globe Winners.png
    imdb_award:
      event_id: "ev0000292"
      event_year: "1944-current"
      winning: true
      type: "tv_series,tv_special,tv_mini_series"
      language: "en"
      sort_by: release.desc
      limit: 9999
