#####################################################
#                  YEARS 7.0                        #
#####################################################

templates:
  Decade:
    smart_label: audience_rating.desc
    sync_mode: sync
    sort_title: zz_<<collection_name>>
    visible_library: true

  Year:
    smart_label: audience_rating.desc
    sync_mode: sync
    sort_title: zzzz_<<collection_name>>
    visible_library: true

# TV shows with a IMDb rating greater than 7.8 from a decade
collections:
  Best of 1940-1970s:
    template: { name: Decade }
    file_poster: config/posters/19401970s.png
    visible_shared: range(03/01-03/31)
    plex_search:
      all:
        year.gt: 1939
        year.lt: 1980
        audience_rating.gte: 7.8

  Best of 1980s:
    template: { name: Decade }
    file_poster: config/posters/1980s.png
    visible_shared: range(01/01-02/31)
    plex_search:
      all:
        year.gt: 1979
        year.lt: 1990
        audience_rating.gte: 7.8

  Best of 1990s:
    template: { name: Decade }
    file_poster: config/posters/1990s.png
    visible_shared: range(07/01-08/30)
    plex_search:
      all:
        year.gt: 1989
        year.lt: 2000
        audience_rating.gte: 7.8

  Best of 2000s:
    template: { name: Decade }
    file_poster: config/posters/2000s.png
    visible_shared: range(04/01-06/30)
    plex_search:
      all:
        year.gt: 1999
        year.lt: 2010
        audience_rating.gte: 7.8

  Best of 2010s:
    template: { name: Decade }
    file_poster: config/posters/2010s.png
    visible_shared: range(11/01-12/31)
    plex_search:
      all:
        year.gt: 2009
        year.lt: 2020
        audience_rating.gte: 7.8

  Best of 2020s:
    template: { name: Decade }
    file_poster: config/posters/2020s.png
    visible_shared: range(09/01-10/31)
    plex_search:
      all:
        year.gt: 2019
        year.lt: 2030
        audience_rating.gte: 7.8

  #######################################################
  #                    DECADES 6.0                      #
  #######################################################

  # Best movies from 2000 and forward according to IMDb with a rating of 7.8 and up
  Best of 2000:
    template: { name: Year }
    file_poster: config/posters/2000.png
    plex_search:
      all:
        year: 2000
        audience_rating.gte: 7.8

  Best of 2001:
    template: { name: Year }
    file_poster: config/posters/2001.png
    plex_search:
      all:
        year: 2001
        audience_rating.gte: 7.8

  Best of 2002:
    template: { name: Year }
    file_poster: config/posters/2002.png
    plex_search:
      all:
        year: 2002
        audience_rating.gte: 7.8

  Best of 2003:
    template: { name: Year }
    file_poster: config/posters/2003.png
    plex_search:
      all:
        year: 2003
        audience_rating.gte: 7.8

  Best of 2004:
    template: { name: Year }
    file_poster: config/posters/2004.png
    plex_search:
      all:
        year: 2004
        audience_rating.gte: 7.8

  Best of 2005:
    template: { name: Year }
    file_poster: config/posters/2005.png
    plex_search:
      all:
        year: 2005
        audience_rating.gte: 7.8

  Best of 2006:
    template: { name: Year }
    file_poster: config/posters/2006.png
    plex_search:
      all:
        year: 2006
        audience_rating.gte: 7.8

  Best of 2007:
    template: { name: Year }
    file_poster: config/posters/2007.png
    plex_search:
      all:
        year: 2007
        audience_rating.gte: 7.8

  Best of 2008:
    template: { name: Year }
    file_poster: config/posters/2008.png
    plex_search:
      all:
        year: 2008
        audience_rating.gte: 7.8

  Best of 2009:
    template: { name: Year }
    file_poster: config/posters/2009.png
    plex_search:
      all:
        year: 2009
        audience_rating.gte: 7.8

  Best of 2010:
    template: { name: Year }
    file_poster: config/posters/2010.png
    visible_shared: range(04/16-04/30)
    plex_search:
      all:
        year: 2010
        audience_rating.gte: 7.8

  Best of 2011:
    template: { name: Year }
    file_poster: config/posters/2011.png
    visible_shared: range(10/23-10/31)
    plex_search:
      all:
        year: 2011
        audience_rating.gte: 7.8

  Best of 2012:
    template: { name: Year }
    file_poster: config/posters/2012.png
    visible_shared: range(06/01-06/15)
    plex_search:
      all:
        year: 2012
        audience_rating.gte: 7.8

  Best of 2013:
    template: { name: Year }
    file_poster: config/posters/2013.png
    visible_shared: range(12/16-12/31)
    plex_search:
      all:
        year: 2013
        audience_rating.gte: 7.8

  Best of 2014:
    template: { name: Year }
    file_poster: config/posters/2014.png
    visible_shared: range(01/01-01/15)
    plex_search:
      all:
        year: 2014
        audience_rating.gte: 7.8

  Best of 2015:
    template: { name: Year }
    file_poster: config/posters/2015.png
    visible_shared: range(06/16-06/22)
    plex_search:
      all:
        year: 2015
        audience_rating.gte: 7.8

  Best of 2016:
    template: { name: Year }
    file_poster: config/posters/2016.png
    visible_shared: range(12/01-12/15)
    plex_search:
      all:
        year: 2016
        audience_rating.gte: 7.8

  Best of 2017:
    template: { name: Year }
    file_poster: config/posters/2017.png
    visible_shared: range(10/01-10/15)
    plex_search:
      all:
        year: 2017
        audience_rating.gte: 7.8

  Best of 2018:
    template: { name: Year }
    file_poster: config/posters/2018.png
    visible_shared: range(02/16-02/28)
    plex_search:
      all:
        year: 2018
        audience_rating.gte: 7.8

  Best of 2019:
    template: { name: Year }
    file_poster: config/posters/2019.png
    visible_shared: range(08/16-08/31)
    plex_search:
      all:
        year: 2019
        audience_rating.gte: 7.8

  Best of 2020:
    template: { name: Year }
    file_poster: config/posters/2020.png
    visible_shared: range(11/16-11/30)
    plex_search:
      all:
        year: 2020
        audience_rating.gte: 7.8

  Best of 2021:
    template: { name: Year }
    file_poster: config/posters/2021.png
    visible_shared: range(09/16-09/31)
    plex_search:
      all:
        year: 2021
        audience_rating.gte: 7.8

  Best of 2022:
    template: { name: Year }
    file_poster: config/posters/2022.png
    visible_shared: range(10/16-10/22)
    plex_search:
      all:
        year: 2022
        audience_rating.gte: 7.8

  Best of 2023:
    template: { name: Year }
    file_poster: config/posters/2023.png
    visible_shared: range(03/16-03/22)
    plex_search:
      all:
        year: 2023
        audience_rating.gte: 7.8
